### PR TITLE
Don't throw strings

### PR DESCRIPTION
**Pull request by LoganDark**
Seriously? Throwing strings?

### CODE REVIEW

**Comment by giuseppemag** [comment]
LoganDark, the course is focused on functional programming, not best practices for industrial-level js programming.

Moreover, as code becomes type safe, exceptions will disappear from your code besides remote boundaries (api payload deserialization). Thus you could consider throwing as a bad practice in itself, and just used here as a placeholder for the time when such poor constructs are deprecated. Dev8 does indeed deprecate exceptions quite a lot, but it will not be until infsen1 and infsen2 that you will be fully able to write exception-free code.


Also, do not be hypercritical. These people know what they are doing, far beyond what you can infer from a bit of code.

**Comment by LoganDark** [comment]
Okay.

Still doesn't change the fact that they are throwing strings.

Nowhere did I say they did not know what they were doing. This is simply a pull request proposing they throw errors instead of strings.

**Comment by giuseppemag** [comment]
I understand, but what is the added value of throwing errors instead of strings then, for the purpose of the course?

I believe that the context of the application is as important as the code, and throwing strings is allowed (but not advised). What kind of problem are you solving with this pull request? Does it balance with the fact that the code is a little more distracting?

**Comment by LoganDark** [comment]
It bugs me that you are throwing strings.

What kind of problem would you be solving by not merging the pull request? Is throwing strings somehow better than throwing errors?

The code may be a little more distracting, but there are much more distracting parts of the code. Take `rev` as an example. I helped a student earlier with this, that is how I found out about this code in the first place.

Anyway, you've made it clear to me that personal preference is of no significance here. The quality of this code is of no significance to me anyway. I find it annoying that I've already spent time here trying to explain myself when you won't even listen.

**Comment by giuseppemag** [comment]
I am more than willing to merge the request, but it seems like a good opportunity for you to learn to motivate your choices beyond personal preference.

I agree with you, and I also do prefer idiomatic over non-idiomatic. This said, the original message you attached to the pull request, which was _Seriously? Throwing strings?_, was highly unprofessional. I would suggest you help me set the record straight: as professionals, we should always motivate things in an objective way and without insulting or unfriendly language. 

Try to provide me with a good, professionally worded reason for your pull request, and stop saying things half way. For example, what is wrong with `rev`? Explain!

**Pull request closed without merging**
